#ifndef VULKANPROJECT_POINTLIGHTSHADOWMAPPIPELINE_H
#define VULKANPROJECT_POINTLIGHTSHADOWMAPPIPELINE_H

namespace vke {
  class PointLightShadowMapPipeline {
  };
} // vke

#endif //VULKANPROJECT_POINTLIGHTSHADOWMAPPIPELINE_H