set(VULKAN_ENGINE_SOURCES
  VulkanEngine.cpp
  VulkanEngine.h
  components/framebuffers/Framebuffer.cpp
  components/framebuffers/Framebuffer.h
  components/framebuffers/StandardFramebuffer.cpp
  components/framebuffers/StandardFramebuffer.h
  components/framebuffers/SwapchainFramebuffer.cpp
  components/framebuffers/SwapchainFramebuffer.h
  components/textures/Texture.cpp
  components/textures/Texture.h
  components/textures/Texture2D.cpp
  components/textures/Texture2D.h
  components/textures/TextureCubemap.cpp
  components/textures/TextureCubemap.h
  components/textures/Texture3D.cpp
  components/textures/Texture3D.h
  components/Window.cpp
  components/Window.h
  core/instance/DebugMessenger.cpp
  core/instance/DebugMessenger.h
  core/instance/Instance.cpp
  core/instance/Instance.h
  core/logicalDevice/LogicalDevice.cpp
  core/logicalDevice/LogicalDevice.h
  core/physicalDevice/PhysicalDevice.cpp
  core/physicalDevice/PhysicalDevice.h
  objects/RenderObject.cpp
  objects/RenderObject.h
  utilities/Buffers.cpp
  utilities/Buffers.h
  objects/Model.cpp
  objects/Model.h
  utilities/Images.cpp
  utilities/Images.h
  components/Camera.cpp
  components/Camera.h
  objects/UniformBuffer.cpp
  objects/UniformBuffer.h
  pipelines/custom/ObjectsPipeline.cpp
  pipelines/custom/ObjectsPipeline.h
  pipelines/Vertex.h
  pipelines/RenderPass.cpp
  pipelines/RenderPass.h
  pipelines/custom/Uniforms.h
  pipelines/custom/GuiPipeline.cpp
  pipelines/custom/GuiPipeline.h
  pipelines/ShaderModule.cpp
  pipelines/ShaderModule.h
  VulkanEngineOptions.h
  components/ImGuiInstance.cpp
  components/ImGuiInstance.h
  components/SwapChain.cpp
  components/SwapChain.h
  pipelines/custom/DotsPipeline.cpp
  pipelines/custom/DotsPipeline.h
  pipelines/GraphicsPipeline.cpp
  pipelines/GraphicsPipeline.h
  pipelines/ComputePipeline.cpp
  pipelines/ComputePipeline.h
  pipelines/Pipeline.cpp
  pipelines/Pipeline.h
  objects/Light.cpp
  objects/Light.h
  pipelines/custom/EllipticalDots.cpp
  pipelines/custom/EllipticalDots.h
  pipelines/custom/NoisyEllipticalDots.cpp
  pipelines/custom/NoisyEllipticalDots.h
  pipelines/custom/CurtainPipeline.cpp
  pipelines/custom/CurtainPipeline.h
  pipelines/custom/BumpyCurtain.cpp
  pipelines/custom/BumpyCurtain.h
  pipelines/custom/CubeMapPipeline.cpp
  pipelines/custom/CubeMapPipeline.h
  pipelines/custom/TexturedPlane.cpp
  pipelines/custom/TexturedPlane.h
  pipelines/custom/GraphicsPipelineStates.h
  pipelines/Particle.h
  pipelines/custom/MagnifyWhirlMosaicPipeline.cpp
  pipelines/custom/MagnifyWhirlMosaicPipeline.h
  pipelines/custom/SnakePipeline.cpp
  pipelines/custom/SnakePipeline.h
  pipelines/custom/CrossesPipeline.cpp
  pipelines/custom/CrossesPipeline.h
  pipelines/custom/SmokePipeline.cpp
  pipelines/custom/SmokePipeline.h
  pipelines/SmokeParticle.h
  pipelines/custom/LinePipeline.cpp
  pipelines/custom/LinePipeline.h
  pipelines/LineVertex.h
  pipelines/custom/MousePickingPipeline.cpp
  pipelines/custom/MousePickingPipeline.h
  pipelines/custom/ObjectHighlightPipeline.cpp
  pipelines/custom/ObjectHighlightPipeline.h
  core/commandBuffer/CommandBuffer.cpp
  core/commandBuffer/CommandBuffer.h
)